from contracting_process.field_level.date_time import date_realistic
from contracting_process.field_level.language import language_code
from contracting_process.field_level.number_checks import positive_number
from contracting_process.field_level.object_checks import exists, non_empty
from contracting_process.field_level.ocid_prefix_check import ocid_prefix
from contracting_process.field_level.document_description_length import description_length

definitions = {
    "ocid": [exists, non_empty, ocid_prefix],
    "id": [exists, non_empty],
    "date": [exists, non_empty, date_realistic],
    "tag": [exists, non_empty],
    "initiationType": [exists, non_empty],
    "parties": [exists, non_empty],
    "parties.name": [exists, non_empty],
    "parties.id": [exists, non_empty],
    "parties.identifier": [exists, non_empty],
    "parties.identifier.scheme": [exists, non_empty],
    "parties.identifier.id": [exists, non_empty],
    "parties.identifier.legalName": [exists, non_empty],
    "parties.identifier.uri": [exists, non_empty],
    "parties.address": [exists, non_empty],
    "parties.address.streetAddress": [exists, non_empty],
    "parties.address.locality": [exists, non_empty],
    "parties.address.region": [exists, non_empty],
    "parties.address.postalCode": [exists, non_empty],
    "parties.address.countryName": [exists, non_empty],
    "parties.roles": [exists, non_empty],
    "buyer": [exists, non_empty],
    "buyer.id": [exists, non_empty],
    "planning": [exists, non_empty],
    "planning.documents.language": [exists, non_empty, language_code],
    "planning.documents.description": [exists, non_empty, description_length],
    "planning.milestones.documents.description": [exists, non_empty, description_length],
    "tender": [exists, non_empty],
    "tender.id": [exists, non_empty],
    "tender.title": [exists, non_empty],
    "tender.description": [exists, non_empty],
    "tender.documents.language": [exists, non_empty, language_code],
    "tender.documents.description": [exists, non_empty, description_length],
    "tender.status": [exists, non_empty],
    "tender.procuringEntity": [exists, non_empty],
    "tender.items": [exists, non_empty],
    "tender.value": [exists, non_empty],
    "tender.value.amount": [exists, non_empty],
    "tender.value.currency": [exists, non_empty],
    "tender.minValue": [exists, non_empty],
    "tender.procurementMethod": [exists, non_empty],
    "tender.mainProcurementCategory": [exists, non_empty],
    "tender.awardCriteria": [exists, non_empty],
    "tender.tenderPeriod": [exists, non_empty],
    "tender.tenderPeriod.startDate": [exists, non_empty, date_realistic],
    "tender.tenderPeriod.endDate": [exists, non_empty, date_realistic],
    "tender.tenderPeriod.maxExtentDate": [exists, non_empty, date_realistic],
    "tender.tenderPeriod.durationInDays": [exists, non_empty, positive_number],
    "tender.awardPeriod": [exists, non_empty],
    "tender.awardPeriod.startDate": [exists, non_empty, date_realistic],
    "tender.awardPeriod.endDate": [exists, non_empty, date_realistic],
    "tender.awardPeriod.maxExtentDate": [exists, non_empty, date_realistic],
    "tender.awardPeriod.durationInDays": [exists, non_empty, positive_number],
    "tender.contractPeriod": [exists, non_empty],
    "tender.contractPeriod.startDate": [exists, non_empty, date_realistic],
    "tender.contractPeriod.endDate": [exists, non_empty, date_realistic],
    "tender.contractPeriod.maxExtentDate": [exists, non_empty, date_realistic],
    "tender.contractPeriod.durationInDays": [exists, non_empty, positive_number],
    "tender.enquiryPeriod.durationInDays": [exists, non_empty, positive_number],
    "tender.enquiryPeriod.startDate": [exists, non_empty, date_realistic],
    "tender.enquiryPeriod.endDate": [exists, non_empty, date_realistic],
    "tender.enquiryPeriod.maxExtentDate": [exists, non_empty, date_realistic],
    "tender.numberOfTenderers": [exists, non_empty, positive_number],
    "tender.tenderers": [exists, non_empty],
    "tender.documents.datePublished": [exists, non_empty, date_realistic],
    "tender.documents.dateModified": [exists, non_empty, date_realistic],
    "tender.milestones.documents.description": [exists, non_empty, description_length],
    "awards": [exists, non_empty],
    "awards.id": [exists, non_empty],
    "awards.title": [exists, non_empty],
    "awards.status": [exists, non_empty],
    "awards.date": [exists, non_empty, date_realistic],
    "awards.value": [exists, non_empty],
    "awards.value.amount": [exists, non_empty],
    "awards.value.currency": [exists, non_empty],
    "awards.suppliers": [exists, non_empty],
    "awards.suppliers.name": [exists, non_empty],
    "awards.suppliers.id": [exists, non_empty],
    "awards.contractPeriod": [exists, non_empty],
    "awards.contractPeriod.startDate": [exists, non_empty, date_realistic],
    "awards.contractPeriod.endDate": [exists, non_empty, date_realistic],
    "awards.contractPeriod.maxExtentDate": [exists, non_empty, date_realistic],
    "awards.contrsctPeriod.durationInDays": [exists, non_empty, positive_number],
    "awards.documents.language": [exists, non_empty, language_code],
    "awards.documents.datePublished": [exists, non_empty, date_realistic],
    "awards.documents.dateModified": [exists, non_empty, date_realistic],
    "awards.documents.description": [exists, non_empty, description_length],
    "contracts": [exists, non_empty],
    "contracts.id": [exists, non_empty],
    "contracts.awardID": [exists, non_empty],
    "contracts.title": [exists, non_empty],
    "contracts.description": [exists, non_empty],
    "contracts.status": [exists, non_empty],
    "contracts.period": [exists, non_empty],
    "contracts.period.startDate": [exists, non_empty, date_realistic],
    "contracts.period.endDate": [exists, non_empty, date_realistic],
    "contracts.period.maxExtentDate": [exists, non_empty, date_realistic],
    "contracts.period.durationInDays": [exists, non_empty],
    "contracts.value": [exists, non_empty],
    "contracts.value.amount": [exists, non_empty],
    "contracts.value.currency": [exists, non_empty],
    "contracts.items": [exists, non_empty],
    "contracts.items.id": [exists, non_empty],
    "contracts.items.description": [exists, non_empty],
    "contracts.items.classification": [exists, non_empty],
    "contracts.items.quantity": [exists, non_empty],
    "contracts.items.unit": [exists, non_empty],
    "contracts.items.unit.scheme": [exists, non_empty],
    "contracts.items.unit.id": [exists, non_empty],
    "contracts.items.unit.name": [exists, non_empty],
    "contracts.items.unit.value": [exists, non_empty],
    "contracts.items.unit.uri": [exists, non_empty],
    "contracts.dateSigned": [exists, non_empty, date_realistic],
    "contracts.documents": [exists, non_empty],
    "contracts.documents.id": [exists, non_empty],
    "contracts.documents.documentType": [exists, non_empty],
    "contracts.documents.title": [exists, non_empty],
    "contracts.documents.description": [exists, non_empty, description_length],
    "contracts.documents.url": [exists, non_empty],
    "contracts.documents.datePublished": [exists, non_empty, date_realistic],
    "contracts.documents.dateModified": [exists, non_empty, date_realistic],
    "contracts.documents.format": [exists, non_empty],
    "contracts.documents.language": [exists, non_empty, language_code],
    "contracts.durationInDays": [exists, non_empty, positive_number],
    "contracts.milestones.dateMet": [exists, non_empty, date_realistic],
    "contracts.milestones.dateModified": [exists, non_empty, date_realistic],
    "contracts.milestones.documents.dateModified": [exists, non_empty, date_realistic],
    "contracts.milestones.documents.datePublished": [exists, non_empty, date_realistic],
    "contracts.milestones.documents.description": [exists, non_empty, description_length],
    "contracts.implementation.transactions.value.amount": [exists, non_empty, positive_number],
    "contracts.implementation.transactions.date": [exists, non_empty, date_realistic],
    "contracts.implementation.documents.dateModified": [exists, non_empty, date_realistic],
    "contracts.implementation.documents.datePublished": [exists, non_empty, date_realistic],
    "contracts.implementation.documents.language": [exists, non_empty, language_code],
    "contracts.implementation.documents.description": [exists, non_empty, description_length],
    "contracts.amendments.date": [exists, non_empty, date_realistic],
    "contracts.amendment.date": [exists, non_empty, date_realistic],
    "contracts.milestones.documents.language": [exists, non_empty, language_code],
    "language": [exists, non_empty, language_code],
    "relatedProcesses": [exists, non_empty],
    "item.unit.value.amount": [exists, non_empty, positive_number],
    "item.quantity": [exists, non_empty, positive_number],
    "planning.documents.datePublished": [exists, non_empty, date_realistic],
    "planning.documents.dateModified": [exists, non_empty, date_realistic],
}
