
import functools

import contracting_process.field_level.checks.date_time as date_time
import contracting_process.field_level.checks.language as language
import contracting_process.field_level.checks.number_checks as number_checks
import contracting_process.field_level.checks.ocid_prefix_check as ocid_prefix_check
import contracting_process.field_level.checks.telephone as telephone
import contracting_process.field_level.checks.document_description_length as document_description_length
import contracting_process.field_level.checks.email as email
import contracting_process.field_level.checks.document_format_codelist as document_format_codelist
import contracting_process.field_level.checks.identifier_scheme as identifier_scheme
import contracting_process.field_level.checks.document_type as document_type

import contracting_process.field_level.checks.exists as exists
import contracting_process.field_level.checks.non_empty as non_empty

coverage_checks = [(exists.calculate, exists.name), (non_empty.calculate, non_empty.name)]

definitions = {
    "ocid": [(ocid_prefix_check.calculate, ocid_prefix_check.name)],
    "id": [],
    "date": [(date_time.calculate, date_time.name)],
    "tag": [],
    "initiationType": [],
    "parties": [],
    "parties.name": [],
    "parties.id": [],
    "parties.identifier": [(identifier_scheme.calculate, identifier_scheme.name)],
    "parties.identifier.scheme": [],
    "parties.identifier.id": [],
    "parties.identifier.legalName": [],
    "parties.identifier.uri": [],
    "parties.additionalIdentifiers": [(identifier_scheme.calculate, identifier_scheme.name)],
    "parties.additionalIdentifiers.scheme": [],
    "parties.additionalIdentifiers.id": [],
    "parties.additionalIdentifiers.legalName": [],
    "parties.additionalIdentifiers.uri": [],
    "parties.address": [],
    "parties.address.streetAddress": [],
    "parties.address.locality": [],
    "parties.address.region": [],
    "parties.address.postalCode": [],
    "parties.address.countryName": [],
    "parties.contactPoint": [],
    "parties.contactPoint.name": [],
    "parties.contactPoint.email": [(email.calculate, email.name)],
    "parties.contactPoint.telephone": [(telephone.calculate, telephone.name)],
    "parties.contactPoint.faxNumber": [(telephone.calculate, telephone.name)],
    "parties.contactPoint.url": [],
    "parties.roles": [],
    "parties.details": [],
    "buyer": [],
    "buyer.name": [],
    "buyer.id": [],
    "buyer.identifier": [(identifier_scheme.calculate, identifier_scheme.name)],
    "buyer.identifier.scheme": [],
    "buyer.identifier.id": [],
    "buyer.identifier.legalName": [],
    "buyer.identifier.uri": [],
    "buyer.address": [],
    "buyer.address.streetAddress": [],
    "buyer.address.locality": [],
    "buyer.address.region": [],
    "buyer.address.postalCode": [],
    "buyer.address.countryName": [],
    "buyer.additionalIdentifiers": [(identifier_scheme.calculate, identifier_scheme.name)],
    "buyer.additionalIdentifiers.scheme": [],
    "buyer.additionalIdentifiers.id": [],
    "buyer.additionalIdentifiers.legalName": [],
    "buyer.additionalIdentifiers.uri": [],
    "buyer.contactPoint.name": [],
    "buyer.contactPoint.email": [(email.calculate, email.name)],
    "buyer.contactPoint.telephone": [(telephone.calculate, telephone.name)],
    "buyer.contactPoint.faxNumber": [(telephone.calculate, telephone.name)],
    "buyer.contactPoint.url": [],
    "planning": [],
    "planning.rationale": [],
    "planning.budget": [],
    "planning.budget.id": [],
    "planning.budget.description": [],
    "planning.budget.amount": [],
    "planning.budget.amount.amount": [],
    "planning.budget.amount.currency": [],
    "planning.budget.project": [],
    "planning.budget.projectID": [],
    "planning.budget.uri": [],
    "planning.budget.source": [],
    "planning.documents": [],
    "planning.documents.id": [],
    "planning.documents.documentType": [(functools.partial(document_type.calculate_section, section='planning'), document_type.name)],
    "planning.documents.title": [],
    "planning.documents.description": [(document_description_length.calculate, document_description_length.name)],
    "planning.documents.url": [],
    "planning.documents.datePublished": [(date_time.calculate, date_time.name)],
    "planning.documents.dateModified": [(date_time.calculate, date_time.name)],
    "planning.documents.format": [(document_format_codelist.calculate, document_format_codelist.name)],
    "planning.documents.language": [(language.calculate, language.name)],
    "planning.milestones": [],
    "planning.milestones.id": [],
    "planning.milestones.title": [],
    "planning.milestones.type": [],
    "planning.milestones.description": [],
    "planning.milestones.code": [],
    "planning.milestones.dueDate": [(date_time.calculate, date_time.name)],
    "planning.milestones.dateMet": [(date_time.calculate, date_time.name)],
    "planning.milestones.dateModified": [(date_time.calculate, date_time.name)],
    "planning.milestones.status": [],
    "planning.milestones.documents": [],
    "planning.milestones.documents.id": [],
    "planning.milestones.documents.documentType": [(functools.partial(document_type.calculate_section, section='planning'), document_type.name)],
    "planning.milestones.documents.title": [],
    "planning.milestones.documents.description": [(document_description_length.calculate, document_description_length.name)],
    "planning.milestones.documents.url": [],
    "planning.milestones.documents.datePublished": [(date_time.calculate, date_time.name)],
    "planning.milestones.documents.dateModified": [(date_time.calculate, date_time.name)],
    "planning.milestones.documents.format": [(document_format_codelist.calculate, document_format_codelist.name)],
    "planning.milestones.documents.language": [(language.calculate, language.name)],
    "tender": [],
    "tender.id": [],
    "tender.title": [],
    "tender.description": [],
    "tender.status": [],
    "tender.procuringEntity": [],
    "tender.procuringEntity.name": [],
    "tender.procuringEntity.id": [],
    "tender.procuringEntity.identifier": [(identifier_scheme.calculate, identifier_scheme.name)],
    "tender.procuringEntity.identifier.scheme": [],
    "tender.procuringEntity.identifier.id": [],
    "tender.procuringEntity.identifier.legalName": [],
    "tender.procuringEntity.identifier.uri": [],
    "tender.procuringEntity.address": [],
    "tender.procuringEntity.address.streetAddress": [],
    "tender.procuringEntity.address.locality": [],
    "tender.procuringEntity.address.region": [],
    "tender.procuringEntity.address.postalCode": [],
    "tender.procuringEntity.address.countryName": [],
    "tender.procuringEntity.additionalIdentifiers": [(identifier_scheme.calculate, identifier_scheme.name)],
    "tender.procuringEntity.additionalIdentifiers.scheme": [],
    "tender.procuringEntity.additionalIdentifiers.id": [],
    "tender.procuringEntity.additionalIdentifiers.legalName": [],
    "tender.procuringEntity.additionalIdentifiers.uri": [],
    "tender.procuringEntity.contactPoint.name": [],
    "tender.procuringEntity.contactPoint.email": [(email.calculate, email.name)],
    "tender.procuringEntity.contactPoint.telephone": [(telephone.calculate, telephone.name)],
    "tender.procuringEntity.contactPoint.faxNumber": [(telephone.calculate, telephone.name)],
    "tender.procuringEntity.contactPoint.url": [],
    "tender.items": [],
    "tender.items.id": [],
    "tender.items.description": [],
    "tender.items.classification": [],
    "tender.items.classification.scheme": [],
    "tender.items.classification.id": [],
    "tender.items.classification.description": [],
    "tender.items.classification.uri": [],
    "tender.items.additionalClassifications": [],
    "tender.items.additionalClassifications.scheme": [],
    "tender.items.additionalClassifications.id": [],
    "tender.items.additionalClassifications.description": [],
    "tender.items.additionalClassifications.uri": [],
    "tender.items.quantity": [],
    "tender.items.unit": [],
    "tender.items.unit.scheme": [],
    "tender.items.unit.id": [],
    "tender.items.unit.name": [],
    "tender.items.unit.value": [],
    "tender.items.unit.value.amount": [],
    "tender.items.unit.value.currency": [],
    "tender.items.unit.uri": [],
    "tender.value": [],
    "tender.value.amount": [],
    "tender.value.currency": [],
    "tender.minValue": [],
    "tender.minValue.amount": [],
    "tender.minValue.currency": [],
    "tender.procurementMethod": [],
    "tender.procurementMethodDetails": [],
    "tender.procurementMethodRationale": [],
    "tender.mainProcurementCategory": [],
    "tender.additionalProcurementCategories": [],
    "tender.awardCriteria": [],
    "tender.awardCriteriaDetails": [],
    "tender.submissionMethod": [],
    "tender.submissionMethodDetails": [],
    "tender.tenderPeriod": [],
    "tender.tenderPeriod.startDate": [(date_time.calculate, date_time.name)],
    "tender.tenderPeriod.endDate": [(date_time.calculate, date_time.name)],
    "tender.tenderPeriod.maxExtentDate": [(date_time.calculate, date_time.name)],
    "tender.tenderPeriod.durationInDays": [(number_checks.calculate, number_checks.name)],
    "tender.enquiryPeriod": [],
    "tender.enquiryPeriod.durationInDays": [(number_checks.calculate, number_checks.name)],
    "tender.enquiryPeriod.startDate": [(date_time.calculate, date_time.name)],
    "tender.enquiryPeriod.endDate": [(date_time.calculate, date_time.name)],
    "tender.enquiryPeriod.maxExtentDate": [(date_time.calculate, date_time.name)],
    "tender.hasEnquiries": [],
    "tender.eligibilityCriteria": [],
    "tender.awardPeriod": [],
    "tender.awardPeriod.startDate": [(date_time.calculate, date_time.name)],
    "tender.awardPeriod.endDate": [(date_time.calculate, date_time.name)],
    "tender.awardPeriod.maxExtentDate": [(date_time.calculate, date_time.name)],
    "tender.awardPeriod.durationInDays": [(number_checks.calculate, number_checks.name)],
    "tender.contractPeriod": [],
    "tender.contractPeriod.startDate": [(date_time.calculate, date_time.name)],
    "tender.contractPeriod.endDate": [(date_time.calculate, date_time.name)],
    "tender.contractPeriod.maxExtentDate": [(date_time.calculate, date_time.name)],
    "tender.contractPeriod.durationInDays": [(number_checks.calculate, number_checks.name)],
    "tender.numberOfTenderers": [(number_checks.calculate, number_checks.name)],
    "tender.tenderers": [],
    "tender.tenderers.name": [],
    "tender.tenderers.id": [],
    "tender.tenderers.identifier": [(identifier_scheme.calculate, identifier_scheme.name)],
    "tender.tenderers.identifier.scheme": [],
    "tender.tenderers.identifier.id": [],
    "tender.tenderers.identifier.legalName": [],
    "tender.tenderers.identifier.uri": [],
    "tender.tenderers.address": [],
    "tender.tenderers.address.streetAddress": [],
    "tender.tenderers.address.locality": [],
    "tender.tenderers.address.region": [],
    "tender.tenderers.address.postalCode": [],
    "tender.tenderers.address.countryName": [],
    "tender.tenderers.additionalIdentifiers": [(identifier_scheme.calculate, identifier_scheme.name)],
    "tender.tenderers.additionalIdentifiers.scheme": [],
    "tender.tenderers.additionalIdentifiers.id": [],
    "tender.tenderers.additionalIdentifiers.legalName": [],
    "tender.tenderers.additionalIdentifiers.uri": [],
    "tender.tenderers.contactPoint.name": [],
    "tender.tenderers.contactPoint.email": [(email.calculate, email.name)],
    "tender.tenderers.contactPoint.telephone": [(telephone.calculate, telephone.name)],
    "tender.tenderers.contactPoint.faxNumber": [(telephone.calculate, telephone.name)],
    "tender.tenderers.contactPoint.url": [],
    "tender.documents": [],
    "tender.documents.id": [],
    "tender.documents.documentType": [(functools.partial(document_type.calculate_section, section='tender'), document_type.name)],
    "tender.documents.title": [],
    "tender.documents.description": [(document_description_length.calculate, document_description_length.name)],
    "tender.documents.url": [],
    "tender.documents.datePublished": [(date_time.calculate, date_time.name)],
    "tender.documents.dateModified": [(date_time.calculate, date_time.name)],
    "tender.documents.format": [(document_format_codelist.calculate, document_format_codelist.name)],
    "tender.documents.language": [(language.calculate, language.name)],
    "tender.documents.datePublished": [(date_time.calculate, date_time.name)],
    "tender.documents.dateModified": [(date_time.calculate, date_time.name)],
    "tender.milestones": [],
    "tender.milestones.id": [],
    "tender.milestones.title": [],
    "tender.milestones.type": [],
    "tender.milestones.description": [],
    "tender.milestones.code": [],
    "tender.milestones.dueDate": [(date_time.calculate, date_time.name)],
    "tender.milestones.dateMet": [(date_time.calculate, date_time.name)],
    "tender.milestones.dateModified": [(date_time.calculate, date_time.name)],
    "tender.milestones.status": [],
    "tender.milestones.documents": [],
    "tender.milestones.documents.id": [],
    "tender.milestones.documents.documentType": [(functools.partial(document_type.calculate_section, section='tender'), document_type.name)],
    "tender.milestones.documents.title": [],
    "tender.milestones.documents.description": [(document_description_length.calculate, document_description_length.name)],
    "tender.milestones.documents.url": [],
    "tender.milestones.documents.datePublished": [(date_time.calculate, date_time.name)],
    "tender.milestones.documents.dateModified": [(date_time.calculate, date_time.name)],
    "tender.milestones.documents.format": [(document_format_codelist.calculate, document_format_codelist.name)],
    "tender.milestones.documents.language": [(language.calculate, language.name)],
    "tender.amendments": [],
    "tender.amendments.date": [(date_time.calculate, date_time.name)],
    "tender.amendments.rationale": [],
    "tender.amendments.id": [],
    "tender.amendments.description": [],
    "tender.amendments.amendsReleaseID": [],
    "tender.amendments.releaseID": [],
    "tender.amendments.changes": [],
    "tender.amendments.changes.property": [],
    "tender.amendments.changes.former_value": [],
    "tender.amendment": [],
    "tender.amendment.date": [(date_time.calculate, date_time.name)],
    "tender.amendment.rationale": [],
    "tender.amendment.id": [],
    "tender.amendment.description": [],
    "tender.amendment.amendsReleaseID": [],
    "tender.amendment.releaseID": [],
    "tender.amendment.changes": [],
    "tender.amendment.changes.property": [],
    "tender.amendment.changes.former_value": [],
    "awards": [],
    "awards.id": [],
    "awards.title": [],
    "awards.description": [],
    "awards.status": [],
    "awards.date": [(date_time.calculate, date_time.name)],
    "awards.value": [],
    "awards.value.amount": [],
    "awards.value.currency": [],
    "awards.supplier": [],
    "awards.supplier.name": [],
    "awards.supplier.id": [],
    "awards.supplier.identifier": [(identifier_scheme.calculate, identifier_scheme.name)],
    "awards.supplier.identifier.scheme": [],
    "awards.supplier.identifier.id": [],
    "awards.supplier.identifier.legalName": [],
    "awards.supplier.identifier.uri": [],
    "awards.supplier.address": [],
    "awards.supplier.address.streetAddress": [],
    "awards.supplier.address.locality": [],
    "awards.supplier.address.region": [],
    "awards.supplier.address.postalCode": [],
    "awards.supplier.address.countryName": [],
    "awards.supplier.additionalIdentifiers": [(identifier_scheme.calculate, identifier_scheme.name)],
    "awards.supplier.additionalIdentifiers.scheme": [],
    "awards.supplier.additionalIdentifiers.id": [],
    "awards.supplier.additionalIdentifiers.legalName": [],
    "awards.supplier.additionalIdentifiers.uri": [],
    "awards.supplier.contactPoint.name": [],
    "awards.supplier.contactPoint.email": [(email.calculate, email.name)],
    "awards.supplier.contactPoint.telephone": [(telephone.calculate, telephone.name)],
    "awards.supplier.contactPoint.faxNumber": [(telephone.calculate, telephone.name)],
    "awards.supplier.contactPoint.url": [],
    "awards.items": [],
    "awards.items.id": [],
    "awards.items.description": [],
    "awards.items.classification": [],
    "awards.items.classification.scheme": [],
    "awards.items.classification.id": [],
    "awards.items.classification.description": [],
    "awards.items.classification.uri": [],
    "awards.items.additionalClassifications": [],
    "awards.items.additionalClassifications.scheme": [],
    "awards.items.additionalClassifications.id": [],
    "awards.items.additionalClassifications.description": [],
    "awards.items.additionalClassifications.uri": [],
    "awards.items.quantity": [],
    "awards.items.unit": [],
    "awards.items.unit.scheme": [],
    "awards.items.unit.id": [],
    "awards.items.unit.name": [],
    "awards.items.unit.value": [],
    "awards.items.unit.value.amount": [],
    "awards.items.unit.value.currency": [],
    "awards.items.unit.uri": [],
    "awards.contractPeriod": [],
    "awards.contractPeriod.startDate": [(date_time.calculate, date_time.name)],
    "awards.contractPeriod.endDate": [(date_time.calculate, date_time.name)],
    "awards.contractPeriod.maxExtentDate": [(date_time.calculate, date_time.name)],
    "awards.contractPeriod.durationInDays": [(number_checks.calculate, number_checks.name)],
    "awards.documents": [],
    "awards.documents.id": [],
    "awards.documents.documentType": [(functools.partial(document_type.calculate_section, section='award'), document_type.name)],
    "awards.documents.title": [],
    "awards.documents.description": [(document_description_length.calculate, document_description_length.name)],
    "awards.documents.url": [],
    "awards.documents.datePublished": [(date_time.calculate, date_time.name)],
    "awards.documents.dateModified": [(date_time.calculate, date_time.name)],
    "awards.documents.format": [(document_format_codelist.calculate, document_format_codelist.name)],
    "awards.documents.language": [(language.calculate, language.name)],
    "awards.documents.language": [],
    "awards.amendments": [],
    "awards.amendments.date": [(date_time.calculate, date_time.name)],
    "awards.amendments.rationale": [],
    "awards.amendments.id": [],
    "awards.amendments.description": [],
    "awards.amendments.amendsReleaseID": [],
    "awards.amendments.releaseID": [],
    "awards.amendments.changes": [],
    "awards.amendments.changes.property": [],
    "awards.amendments.changes.former_value": [],
    "awards.amendment": [],
    "awards.amendment.date": [(date_time.calculate, date_time.name)],
    "awards.amendment.rationale": [],
    "awards.amendment.id": [],
    "awards.amendment.description": [],
    "awards.amendment.amendsReleaseID": [],
    "awards.amendment.releaseID": [],
    "awards.amendment.changes": [],
    "awards.amendment.changes.property": [],
    "awards.amendment.changes.former_value": [],
    "contracts": [],
    "contracts.id": [],
    "contracts.awardID": [],
    "contracts.title": [],
    "contracts.description": [],
    "contracts.status": [],
    "contracts.period": [],
    "contracts.period.startDate": [(date_time.calculate, date_time.name)],
    "contracts.period.endDate": [(date_time.calculate, date_time.name)],
    "contracts.period.maxExtentDate": [(date_time.calculate, date_time.name)],
    "contracts.period.durationInDays": [],
    "contracts.value": [],
    "contracts.value.amount": [],
    "contracts.value.currency": [],
    "contracts.items": [],
    "contracts.items.id": [],
    "contracts.items.description": [],
    "contracts.items.classification": [],
    "contracts.items.classification.scheme": [],
    "contracts.items.classification.id": [],
    "contracts.items.classification.description": [],
    "contracts.items.classification.uri": [],
    "contracts.items.additionalClassifications": [],
    "contracts.items.additionalClassifications.scheme": [],
    "contracts.items.additionalClassifications.id": [],
    "contracts.items.additionalClassifications.description": [],
    "contracts.items.additionalClassifications.uri": [],
    "contracts.items.quantity": [],
    "contracts.items.unit": [],
    "contracts.items.unit.scheme": [],
    "contracts.items.unit.id": [],
    "contracts.items.unit.name": [],
    "contracts.items.unit.value": [],
    "contracts.items.unit.value.amount": [],
    "contracts.items.unit.value.currency": [],
    "contracts.items.unit.uri": [],
    "contracts.dateSigned": [(date_time.calculate, date_time.name)],
    "contracts.documents.id": [],
    "contracts.documents.documentType": [(functools.partial(document_type.calculate_section, section='contract'), document_type.name)],
    "contracts.documents.title": [],
    "contracts.documents.description": [(document_description_length.calculate, document_description_length.name)],
    "contracts.documents.url": [],
    "contracts.documents.datePublished": [(date_time.calculate, date_time.name)],
    "contracts.documents.dateModified": [(date_time.calculate, date_time.name)],
    "contracts.documents.format": [(document_format_codelist.calculate, document_format_codelist.name)],
    "contracts.documents.language": [(language.calculate, language.name)],
    "contracts.documents.language": [],
    "contracts.implementation": [(document_description_length.calculate, document_description_length.name)],
    "contracts.implementation.transactions.id": [],
    "contracts.implementation.transactions.source": [],
    "contracts.implementation.transactions.date": [(date_time.calculate, date_time.name)],
    "contracts.implementation.transactions.value.amount": [(number_checks.calculate, number_checks.name)],
    "contracts.implementation.transactions.value.currency": [],
    "contracts.implementation.transactions.payer": [],
    "contracts.implementation.transactions.payer.name": [],
    "contracts.implementation.transactions.payer.id": [],
    "contracts.implementation.transactions.payer.identifier": [(identifier_scheme.calculate, identifier_scheme.name)],
    "contracts.implementation.transactions.payer.identifier.scheme": [],
    "contracts.implementation.transactions.payer.identifier.id": [],
    "contracts.implementation.transactions.payer.identifier.legalName": [],
    "contracts.implementation.transactions.payer.identifier.uri": [],
    "contracts.implementation.transactions.payer.address": [],
    "contracts.implementation.transactions.payer.address.streetAddress": [],
    "contracts.implementation.transactions.payer.address.locality": [],
    "contracts.implementation.transactions.payer.address.region": [],
    "contracts.implementation.transactions.payer.address.postalCode": [],
    "contracts.implementation.transactions.payer.address.countryName": [],
    "contracts.implementation.transactions.payer.additionalIdentifiers": [(identifier_scheme.calculate, identifier_scheme.name)],
    "contracts.implementation.transactions.payer.additionalIdentifiers.scheme": [],
    "contracts.implementation.transactions.payer.additionalIdentifiers.id": [],
    "contracts.implementation.transactions.payer.additionalIdentifiers.legalName": [],
    "contracts.implementation.transactions.payer.additionalIdentifiers.uri": [],
    "contracts.implementation.transactions.payer.contactPoint.name": [],
    "contracts.implementation.transactions.payer.contactPoint.email": [(email.calculate, email.name)],
    "contracts.implementation.transactions.payer.contactPoint.telephone": [(telephone.calculate, telephone.name)],
    "contracts.implementation.transactions.payer.contactPoint.faxNumber": [(telephone.calculate, telephone.name)],
    "contracts.implementation.transactions.payer.contactPoint.url": [],
    "contracts.implementation.transactions.payee": [],
    "contracts.implementation.transactions.payee.name": [],
    "contracts.implementation.transactions.payee.id": [],
    "contracts.implementation.transactions.payee.identifier": [(identifier_scheme.calculate, identifier_scheme.name)],
    "contracts.implementation.transactions.payee.identifier.scheme": [],
    "contracts.implementation.transactions.payee.identifier.id": [],
    "contracts.implementation.transactions.payee.identifier.legalName": [],
    "contracts.implementation.transactions.payee.identifier.uri": [],
    "contracts.implementation.transactions.payee.address": [],
    "contracts.implementation.transactions.payee.address.streetAddress": [],
    "contracts.implementation.transactions.payee.address.locality": [],
    "contracts.implementation.transactions.payee.address.region": [],
    "contracts.implementation.transactions.payee.address.postalCode": [],
    "contracts.implementation.transactions.payee.address.countryName": [],
    "contracts.implementation.transactions.payee.additionalIdentifiers": [(identifier_scheme.calculate, identifier_scheme.name)],
    "contracts.implementation.transactions.payee.additionalIdentifiers.scheme": [],
    "contracts.implementation.transactions.payee.additionalIdentifiers.id": [],
    "contracts.implementation.transactions.payee.additionalIdentifiers.legalName": [],
    "contracts.implementation.transactions.payee.additionalIdentifiers.uri": [],
    "contracts.implementation.transactions.payee.contactPoint.name": [],
    "contracts.implementation.transactions.payee.contactPoint.email": [(email.calculate, email.name)],
    "contracts.implementation.transactions.payee.contactPoint.telephone": [(telephone.calculate, telephone.name)],
    "contracts.implementation.transactions.payee.contactPoint.faxNumber": [(telephone.calculate, telephone.name)],
    "contracts.implementation.transactions.payee.contactPoint.url": [],
    "contracts.implementation.transactions.uri": [],
    "contracts.implementation.transactions.amount": [],
    "contracts.implementation.transactions.amount.amount": [],
    "contracts.implementation.transactions.currency": [],
    "contracts.implementation.transactions.providerOrganization.identifier": [(identifier_scheme.calculate, identifier_scheme.name)],
    "contracts.implementation.transactions.providerOrganization.identifier.scheme": [],
    "contracts.implementation.transactions.providerOrganization.identifier.id": [],
    "contracts.implementation.transactions.providerOrganization.identifier.legalName": [],
    "contracts.implementation.transactions.providerOrganization.identifier.uri": [],
    "contracts.implementation.transactions.receiverOrganization.identifier": [(identifier_scheme.calculate, identifier_scheme.name)],
    "contracts.implementation.transactions.receiverOrganization.identifier.scheme": [],
    "contracts.implementation.transactions.receiverOrganization.identifier.id": [],
    "contracts.implementation.transactions.receiverOrganization.identifier.legalName": [],
    "contracts.implementation.transactions.receiverOrganization.identifier.uri": [],
    "contracts.implementation.milestones": [],
    "contracts.implementation.milestones.id": [],
    "contracts.implementation.milestones.title": [],
    "contracts.implementation.milestones.type": [],
    "contracts.implementation.milestones.description": [],
    "contracts.implementation.milestones.code": [],
    "contracts.implementation.milestones.dueDate": [(date_time.calculate, date_time.name)],
    "contracts.implementation.milestones.dateMet": [(date_time.calculate, date_time.name)],
    "contracts.implementation.milestones.dateModified": [(date_time.calculate, date_time.name)],
    "contracts.implementation.milestones.status": [],
    "contracts.implementation.milestones.documents": [],
    "contracts.implementation.milestones.documents.id": [],
    "contracts.implementation.milestones.documents.documentType": [
        (functools.partial(document_type.calculate_section, section='implementation'), document_type.name)
    ],
    "contracts.implementation.milestones.documents.title": [],
    "contracts.implementation.milestones.documents.description": [
        (document_description_length.calculate, document_description_length.name)
    ],
    "contracts.implementation.milestones.documents.url": [],
    "contracts.implementation.milestones.documents.datePublished": [(date_time.calculate, date_time.name)],
    "contracts.implementation.milestones.documents.dateModified": [(date_time.calculate, date_time.name)],
    "contracts.implementation.milestones.documents.format": [(document_format_codelist.calculate, document_format_codelist.name)],
    "contracts.implementation.milestones.documents.language": [(language.calculate, language.name)],
    "contracts.implementation.documents": [],
    "contracts.implementation.documents.id": [],
    "contracts.implementation.documents.documentType": [
        (functools.partial(document_type.calculate_section, section='implementation'), document_type.name)
    ],
    "contracts.implementation.documents.title": [],
    "contracts.implementation.documents.description": [(document_description_length.calculate, document_description_length.name)],
    "contracts.implementation.documents.url": [],
    "contracts.implementation.documents.datePublished": [(date_time.calculate, date_time.name)],
    "contracts.implementation.documents.dateModified": [(date_time.calculate, date_time.name)],
    "contracts.implementation.documents.format": [(document_format_codelist.calculate, document_format_codelist.name)],
    "contracts.implementation.documents.language": [(language.calculate, language.name)],
    "contracts.relatedProcesses": [],
    "contracts.relatedProcesses.id": [],
    "contracts.relatedProcesses.relationship": [],
    "contracts.relatedProcesses.title": [],
    "contracts.relatedProcesses.scheme": [],
    "contracts.relatedProcesses.identifier": [],
    "contracts.relatedProcesses.uri": [],
    "contracts.milestones": [],
    "contracts.milestones.id": [],
    "contracts.milestones.title": [],
    "contracts.milestones.type": [],
    "contracts.milestones.description": [],
    "contracts.milestones.code": [],
    "contracts.milestones.dueDate": [(date_time.calculate, date_time.name)],
    "contracts.milestones.dateMet": [(date_time.calculate, date_time.name)],
    "contracts.milestones.dateModified": [(date_time.calculate, date_time.name)],
    "contracts.milestones.status": [],
    "contracts.milestones.documents": [],
    "contracts.milestones.documents.id": [],
    "contracts.milestones.documents.documentType": [
        (functools.partial(document_type.calculate_section, section='contract'), document_type.name)
    ],
    "contracts.milestones.documents.title": [],
    "contracts.milestones.documents.description": [(document_description_length.calculate, document_description_length.name)],
    "contracts.milestones.documents.url": [],
    "contracts.milestones.documents.datePublished": [(date_time.calculate, date_time.name)],
    "contracts.milestones.documents.dateModified": [(date_time.calculate, date_time.name)],
    "contracts.milestones.documents.format": [(document_format_codelist.calculate, document_format_codelist.name)],
    "contracts.milestones.documents.language": [(language.calculate, language.name)],
    "contracts.amendments": [],
    "contracts.amendments.date": [(date_time.calculate, date_time.name)],
    "contracts.amendments.rationale": [],
    "contracts.amendments.id": [],
    "contracts.amendments.description": [],
    "contracts.amendments.amendsReleaseID": [],
    "contracts.amendments.releaseID": [],
    "contracts.amendments.changes": [],
    "contracts.amendments.changes.property": [],
    "contracts.amendments.changes.former_value": [],
    "contracts.amendment": [],
    "contracts.amendment.date": [(date_time.calculate, date_time.name)],
    "contracts.amendment.rationale": [],
    "contracts.amendment.id": [],
    "contracts.amendment.description": [],
    "contracts.amendment.amendsReleaseID": [],
    "contracts.amendment.releaseID": [],
    "contracts.amendment.changes": [],
    "contracts.amendment.changes.property": [],
    "contracts.amendment.changes.former_value": [],
    "language": [],
    "relatedProcesses": [],
    "relatedProcesses.id": [],
    "relatedProcesses.relationship": [],
    "relatedProcesses.title": [],
    "relatedProcesses.scheme": [],
    "relatedProcesses.identifier": [],
    "relatedProcesses.uri": []
}
