name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: pip
          cache-dependency-path: '**/requirements*.txt'
      - run: pip install -r requirements_dev.txt
      - run: |
          psql postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres -v ON_ERROR_STOP=1 \
            -c "CREATE EXTENSION btree_gin" \
            -f pelican/migrations/*.sql \
            -c "\copy exchange_rates (valid_on, rates) from 'pelican/static/exchange_rates_dump.csv' delimiter ',' csv header;"
      - env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
          KINGFISHER_PROCESS_DATABASE_URL: postgresql://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres
          TEST_URL: http://localhost:${{ job.services.httpbin.ports[8080] }}
        # For requests.get() in pelican.util.codelists._get() (from unittest tests).
        run: |
          coverage run --source=contracting_process,dataset,manage,pelican,time_variance,workers -m pytest -W error -W ignore::ResourceWarning -rs
      - uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432/tcp
      rabbitmq:
        image: rabbitmq:latest
        options: >-
          --health-cmd "rabbitmq-diagnostics -q check_running"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5672/tcp
      httpbin:
        image: mccutchen/go-httpbin:latest
        ports:
          - 8080/tcp
